# Project information
site_name: RingCentral Unified CRM extension for Chrome and Edge
site_url: https://github.com/ringcentral/rc-unified-crm-extension

# Repository
repo_url: https://github.com/ringcentral/rc-unified-crm-extension
repo_name: ringcentral/rc-unified-crm-extension
edit_uri: tree/master/docs
docs_dir: docs

theme:
  name: material
  features:
      - navigation.path
      - navigation.sections
      - navigation.expand
      - navigation.tabs
      - search.sharing
      - search.highlight
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ringcentral
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ringcentraldevs
extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - mdx_include
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji 
       emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "2023-2024 RingCentral, Inc. All rights reserved."

nav:
- 'Home': index.md
- 'Installation':
  - 'Download': getting-started.md
  - 'Connecting to your CRM': 
     - 'Bullhorn': bullhorn.md
     - 'Clio': clio.md
     - 'Insightly': insightly.md
     - 'Pipedrive': pipedrive.md
     - 'Redtail CRM': redtail.md
- 'User guide':
  - 'Accessing the extension': users/access.md
  - 'Making and receiving calls': users/making-calls.md
  - 'Logging calls': users/logging.md
  - 'Sending SMS': users/sms.md
  - 'Presence': users/presence.md
  - 'Settings': users/settings.md
- 'Developer guide':
  - 'Introduction': developers/index.md
  - 'Quick start': developers/quick-start.md
  - 'Manifest': developers/manifest.md
  - 'Authorization': developers/auth.md
  - 'Build and deployment': developers/deploy.md
  - 'Adapter': 
    - 'Overview and interfaces': developers/adapter.md
    - 'Contact matching': developers/contact-matching.md
    - 'Logging phone calls': developers/logging-calls.md
    - 'Logging SMS': developers/logging-sms.md
    - 'Placeholder contacts': developers/placeholder-contacts.md
    - 'Unauthorizing users': developers/unauthorization.md
    - 'OpenAPI specification': developers/openapi.md
- 'Support':
  - 'Troubleshooting': support.md
  - 'Feedback': feedback.md
  - 'Release notes': release-notes.md
