# Project information
site_name: RingCentral Unified CRM extension for Chrome and Edge
site_url: https://github.com/ringcentral/rc-unified-crm-extension

# Repository
repo_url: https://github.com/ringcentral/rc-unified-crm-extension
repo_name: ringcentral/rc-unified-crm-extension
edit_uri: tree/master/docs
docs_dir: docs

theme:
  name: material
  features:
      - navigation.path
#      - navigation.sections
      - search.sharing
      - search.highlight
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ringcentral
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ringcentraldevs
extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
#  - glightbox

copyright: "2023 RingCentral, Inc. All rights reserved."

nav:
- 'Home': index.md
- 'Installation': getting-started.md
- 'Connecting to your CRM': 
   - 'Bullhorn': bullhorn.md
   - 'Clio': clio.md
   - 'Insightly': insightly.md
   - 'Pipedrive': pipedrive.md
   - 'Redtail CRM': redtail.md
- 'Configuration options': configuration.md
- 'User guide': user-guide.md
- 'Support and troubleshooting': support.md
